"""
Lorenzo Tonet SM3800123
Emanuele Toso SM3800114

environment_generators.py

This file contains the functions used to generate random SailingEnv environments. 
The functions are used to create random checkpoints and wind fields, as well as to create a random initial positions for the boat.
The exact functioning of the functions is described under each func. 
Please note: the env generated by these functions is a SailingEnv object, for our code we will need to wrap it in a FlattenSailingObs object, 
which is done in the code that calls these functions. This is done because it's easier to change parameters of the env as a Sailing Env object.

The functions are:

create_random_environment_old()
create_random_environment()

"""

import numpy as np
import random

from .environment import SailingEnv
from .map_elements import Checkpoint


def create_random_environment(config: dict, verbose:bool = True) -> SailingEnv:
    """
    Inputs:
    - config: dictionary containing the configuration of the environment. loaded from config.yaml
    - verbose: if True, print the checkpoints positions and radius

    Output:
    - env: a random SailingEnv environment with random checkpoints

    Current version of the create_random_environment function. This function generates random checkpoints and wind fields, 
    as well as a random initial position for the boat. 
    The idea behind the algorithm is the following:
    1. Generate n+1 random positions for checkpoints (n checkpoints + 1 for the starting position). these positions are generated sequentially in the map, 
       but with a minimum distance of 20 between them
    2. Choose a random starting position for the boat from the generated positions
    3. Choose the next checkpoints from the remaining positions. 'ckp_probability' times (modifiable from the config.yaml) 
       the next checkpoint will be the closest one, otherwise it will be a random one from the remaining. 
    4. Change randomly the initial wind vector of the environment
    """
    checkpoints = []

    # define the number of checkpoints to generate
    if config["train"]["env"]["variable_n_checkpoints"]:
        n_checkpoints = np.random.randint(1, config["train"]["env"]["n_checkpoints"] + 1)  # random number of checkpoints between 1 and n_checkpoints
    else:
        n_checkpoints = config["train"]["env"]["n_checkpoints"]
    
    if verbose: print("=====NEW ENVIRONMENT=====")

    # generate n+1 random positions for checkpoints (n checkpoints + 1 for the starting position)
    ckp_positions = []
    while len(ckp_positions) < n_checkpoints+1:
        # random position in the map
        x = np.random.randint(0, config["map_width"])
        y = np.random.randint(0, config["map_height"])

        # compute the distance from all existing checkpoints
        distances = [np.linalg.norm(np.array([x, y]) - np.array(pos)) for pos in ckp_positions]
        if all(dist > 20 for dist in distances):  # minimum distance of 20
            ckp_positions.append((x, y))

    # choose a random starting position for the boat from the generated positions
    start_pos = ckp_positions.pop(np.random.randint(0, len(ckp_positions)))

    # choose the next checkpoints from the remaining positions. 
    # config['train']['env']['ckp_probability'] times the next checkpoint will be the closest one, 
    # otherwise it will be a random one from the remaining ones
    next_checkpoints = []
    while len(next_checkpoints) < n_checkpoints:
        if np.random.rand() < config['train']['env']['ckp_probability']:
            # choose the closest checkpoint
            distances = [np.linalg.norm(np.array(start_pos) - np.array(pos)) for pos in ckp_positions]
            closest_idx = np.argmin(distances)
            next_checkpoints.append(ckp_positions.pop(closest_idx))
        else:
            # choose a random checkpoint
            random_idx = np.random.randint(0, len(ckp_positions))
            next_checkpoints.append(ckp_positions.pop(random_idx))

    radius = 5.0
    for i, (x, y) in enumerate(next_checkpoints):
        checkpoints.append(Checkpoint(position=np.array([int(x), int(y)]), radius=radius, number = i+1))
        if verbose:print(f"Checkpoint {i+1}: position=({x:.2f}, {y:.2f}), radius={radius}, number={i+1}")
    if verbose:print("=========================")

    # change randomly the initial wind vector of the environment
    config["initial_wind"] = np.array([np.random.uniform(config["train"]["env"]["wind_range"][0], config["train"]["env"]["wind_range"][1]), np.random.uniform(config["train"]["env"]["wind_range"][0], config["train"]["env"]["wind_range"][1])])
    if random.random() < 0.5:
        config["initial_wind"][0] *= -1
    if random.random() < 0.5:
        config["initial_wind"][1] *= -1

    # create the environment
    env = SailingEnv(config=config, checkpoints=checkpoints, render_mode=config["mode"])
 
    env.initial_boat_position = np.array(start_pos)

    return env


def create_random_environment_old(config: dict, verbose:bool = True) -> SailingEnv:
    """
    Inputs:
    - config: dictionary containing the configuration of the environment. loaded from config.yaml
    - verbose: if True, print the checkpoints positions and radius

    Output:
    - env: a random SailingEnv environment with random checkpoints

    This is an old version of the create_random_environment function. We are keeping this because environments are easier for the agent
    than the new version, and sometimes we want to test the agent on easier envs.
    We split the map in n+1 vertical zones, where n is the number of checkpoints. The first zone is for the starting position of the boat, 
    the second zone is for the first checkpoint, and so on. The biggest limitation is that the boat only learns to go right, even if we
    were to rotate the map so that it learns to go in other directions the checkpoints would all be generally in the same direction.
    create_random_environment() is a straight improvement in this sense.
    """
    checkpoints = []

    # define the number of checkpoints to generate
    if config["train"]["env"]["variable_n_checkpoints"]:
        n_checkpoints = np.random.randint(1, config["train"]["env"]["n_checkpoints"] + 1)  # random number of checkpoints between 1 and n_checkpoints
    else:
        n_checkpoints = config["train"]["env"]["n_checkpoints"]

    # compute the width of each zone (the height is the same as the map height)
    zone_width = config["map_width"] / (n_checkpoints + 1)
    
    if verbose: print("=====NEW ENVIRONMENT=====")

    # for each checkpoint, generate a random position in the corresponding zone
    for i in range(n_checkpoints):
        
        current_zone_start = (i + 1) * zone_width
        current_zone_end = (i + 2) * zone_width

        x = int(np.random.randint(current_zone_start, current_zone_end))
        y = int(np.random.randint(0, config["map_height"]))

        radius = 5.0
        checkpoints.append(Checkpoint(position=np.array([int(x), int(y)]), radius=radius, number = i+1))
        
        if verbose:print(f"Checkpoint {i+1}: position=({x:.2f}, {y:.2f}), radius={radius}, number={i+1}")
    if verbose:print("=========================")
    
    # create the environment
    env = SailingEnv(config=config, checkpoints=checkpoints, render_mode=config["mode"])

    # change randomly the initial position of the boat inside the first zone
    env.initial_boat_position = np.array([
        int(np.random.randint(0, zone_width)),
        int(np.random.randint(0, config["map_height"]))
    ])

    return env
