
max_speed: float = 10.0,
sail_rotation_speed: float = 0.1,
boat_rotation_speed: float = 0.05,
initial_sail_angle: float = 0.0,
initial_boat_angle: float = 0.0,
initial_position: np.ndarray | None,

# Map configuration
map_width: int = 100,
map_height: int = 100,
water_friction: float = 3.0,

# Simulation configuration
dt: float = 0.1,
max_steps: int = 2_000_000,

# Rendering configuration
window_width: int = 600,
window_height: int = 600,
render_fps: int = 30,

self.polar_diagram_vals: np.array([(0, 0), (52, 5.58), (60, 5.89), (75, 6.11), (90, 6.15), (110, 6.24), (120, 6.11), (135, 5.46), (150, 4.60), (180, 4.0)])
self.plot: False
